name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Change permission test
      run: chmod +x ./triangle_test.sh
      
    - name: Change permission app
      run: chmod +x ./triangle.sh
        
    - name: Run a test for triangle
      run: ./triangle_test.sh ./triangle.sh
